package slotmachineproject;
//Any code that isn't reference that I didn't write myself is generate by scene builder
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Paddy
 */
import java.awt.Image;
import java.awt.EventQueue;
import java.io.File;
import java.util.ArrayList;
import java.util.Random;
import java.util.concurrent.TimeUnit;
import javax.imageio.ImageIO;
import javax.swing.*;
//This method creates the GUI and extends and is creating an instance of SlotMachineMethods.
public class SlotMachineGUI  extends javax.swing.JFrame {
    SlotMachineMethods smm = new SlotMachineMethods();
//These define the images
     Image slotMachineKronk;
     Image num7;
     Image slotMachineBanana;
     Image leverUp;
     Image leverDown;
    /**
     * Creates new form SlotMachineGUI
     */
    public SlotMachineGUI() {
        initComponents();
        smm.ScoreDetails = new ArrayList<>();
        smm.f = new File("score.dat");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slotMachineKronklbl = new javax.swing.JLabel();
        firstSlotPlacelbl = new javax.swing.JLabel();
        slotMachineBananalbl = new javax.swing.JLabel();
        slotMachinelbl = new javax.swing.JLabel();
        slotMachinebtn = new javax.swing.JButton();
        insertCoinbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(564, 524));
        setSize(new java.awt.Dimension(200, 200));
        getContentPane().setLayout(null);

        slotMachineKronklbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slotmachineproject/images/slotMachineKronk.jpg"))); // NOI18N
        getContentPane().add(slotMachineKronklbl);
        slotMachineKronklbl.setBounds(300, 230, 50, 40);

        firstSlotPlacelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slotmachineproject/images/slotNum7.png"))); // NOI18N
        firstSlotPlacelbl.setBounds(40, 20, 20, 20);
        getContentPane().add(firstSlotPlacelbl);
        firstSlotPlacelbl.setBounds(180, 220, 40, 60);

        slotMachineBananalbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slotmachineproject/images/slotMachineBanana.png"))); // NOI18N
        getContentPane().add(slotMachineBananalbl);
        slotMachineBananalbl.setBounds(240, 230, 40, 30);

        slotMachinelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slotmachineproject/images/slotMachine.png"))); // NOI18N
        getContentPane().add(slotMachinelbl);
        slotMachinelbl.setBounds(140, 130, 240, 200);

        slotMachinebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slotmachineproject/images/leverUp.png"))); // NOI18N
        slotMachinebtn.setToolTipText("");
        slotMachinebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slotMachinebtnActionPerformed(evt);
            }
        });
        getContentPane().add(slotMachinebtn);
        slotMachinebtn.setBounds(380, 130, 81, 260);

        insertCoinbtn.setBackground(new java.awt.Color(20, 20, 20));
        insertCoinbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slotmachineproject/images/coin2.png"))); // NOI18N
        insertCoinbtn.setMaximumSize(new java.awt.Dimension(50, 50));
        insertCoinbtn.setMinimumSize(new java.awt.Dimension(50, 50));
        insertCoinbtn.setPreferredSize(new java.awt.Dimension(50, 50));
        insertCoinbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCoinbtnActionPerformed(evt);
            }
        });
        getContentPane().add(insertCoinbtn);
        insertCoinbtn.setBounds(150, 330, 50, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Random number generator
    public void changeSlotImage(){
        Random randy = new Random();

        int randyNo = randy.nextInt(2);
        switch (randyNo) {
                    case 0:
                        firstSlotPlacelbl.setIcon(new ImageIcon(getClass().getResource("/slotmachineproject/images/slotMachineKronk.png")));
                        break;
                    case 1:
                         firstSlotPlacelbl.setIcon(new ImageIcon(getClass().getResource("/slotmachineproject/images/slotMachineKronk.png")));
                        break;
                    case 2:
                         firstSlotPlacelbl.setIcon(new ImageIcon(getClass().getResource("/slotmachineproject/images/slotMachineKronk.png")));
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Error!", "Error chun!", JOptionPane.ERROR_MESSAGE);
                        break;
                }
}
    //Perform and action when the slotMachinebtn is clicked
    private void slotMachinebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slotMachinebtnActionPerformed
        // TODO add your handling code here:
       
           //
        if(evt.getSource()==slotMachinebtn){
            //got help from Ryan Madigan (3rd year games dev)
            try
            {
                //image by default is this
                leverUp = ImageIO.read(getClass().getResource("/slotmachineproject/images/leverUp.png"));
                //then is changed to this
                leverDown= ImageIO.read(getClass().getResource("/slotmachineproject/images/leverDown.png"));
                
                slotMachinebtn.setIcon(new ImageIcon(leverUp));  
                Thread.sleep(1);
                slotMachinebtn.setIcon(new ImageIcon(leverDown));
                smm.takeMoney();
                slotMachinebtn.setIcon(new ImageIcon(leverUp));
                
                 
               //I got the images from google images and I then cropped and edited myself
                slotMachineKronk = ImageIO.read(getClass().getResource("/slotmachineproject/images/slotMachineKronk.png"));
                num7 = ImageIO.read(getClass().getResource("/slotmachineproject/images/slotNum7.png"));
                slotMachineBanana = ImageIO.read(getClass().getResource("/slotmachineproject/images/slotMachineBanana.png"));
                
            }//It catches exception
            catch(Exception ex)
                
                
            {//Prints out the exception
                System.out.print(ex);
            }
            
        }//Should change slot image
        changeSlotImage();
    }//GEN-LAST:event_slotMachinebtnActionPerformed

    private void insertCoinbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCoinbtnActionPerformed
        // TODO add your handling code here:
        smm.addMoney(1);
    }//GEN-LAST:event_insertCoinbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SlotMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SlotMachineGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstSlotPlacelbl;
    private javax.swing.JButton insertCoinbtn;
    private javax.swing.JLabel slotMachineBananalbl;
    private javax.swing.JLabel slotMachineKronklbl;
    private javax.swing.JButton slotMachinebtn;
    private javax.swing.JLabel slotMachinelbl;
    // End of variables declaration//GEN-END:variables
}
